nomenclature:
  name: buy_and_sell
  verboseName: Buy & Sell
baseUrls:
  http: buy_and_sell/
  static: buy_and_sell/
isApi: true
description: Classifieds, by and for the students
acceptables:
  roles:
  - name: Student
    activeStatuses:
    - IS_ACTIVE
    - HAS_BEEN_ACTIVE
categorisation:
  - name: Electronics
    slug: electronics
    categories:
      - name: Mobiles & Accessories
        slug: mobile_accessories
      - name: Computers & Accessories
        slug: computer_accessories
      - name: Others
        slug: electronics_others
  - name: Books
    slug: books
    categories:
      - name: Fiction
        slug: fiction
      - name: Non-fiction
        slug: non_fiction
      - name: Academic
        slug: books_academic
      - name: Others
        slug: books_others
  - name: Academic
    slug: academic
    categories:
      - name: Drafters
        slug: drafters
      - name: Lab coats
        slug: lab_coats
      - name: Others
        slug: academic_others
  - name: Bicycles
    slug: bicycles
  - name: Miscellaneous
    slug: miscellaneous
