# Generated by Django 2.1.1 on 2018-09-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
