# Generated by Django 3.2 on 2023-01-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell', '0003_auto_20230117_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestproduct',
            old_name='is_for_rental',
            new_name='is_rental',
        ),
        migrations.RenameField(
            model_name='saleproduct',
            old_name='is_for_rental',
            new_name='is_rental',
        ),
    ]
