# Generated by Django 3.2 on 2023-02-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell', '0004_auto_20230120_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestproduct',
            name='periodicity',
            field=models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly'), ('lfs', 'Lifespan')], default='lfs', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='periodicity',
            field=models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly'), ('lfs', 'Lifespan')], default='lfs', max_length=10),
        ),
    ]
